<?php

namespace Og\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerHasMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerHasMediaRepository extends EntityRepository
{
}